name: AdminProtect
main: TSt\AdminProtect\Loader
api: 4.0.0
version: 2.0.0-beta-1
authors: ["WeekThor"]
description: "Protect the administrator or player with permissions from being banned and kicked and prevent offline ban"
softdepend: [BanInfo]
permissions:
  adminprotect.ban.protect:
    description: "Protection from /ban"
    default: op
  adminprotect.ban.use:
    description: "Access to use /ban"
    default: op
  adminprotect.ban.use.offline:
    description: "Access to ban offline players"
    default: op
  adminprotect.ban.use.protected:
    description: "Access to ban players with protection"
    default: op
  adminprotect.tempban.protect:
    description: "Protection from /tempban"
    default: op
  adminprotect.tempban.use:
    description: "Access to use /tempban command"
    default: op
  adminprotect.tempban.use.offline:
    description: "Access to temporary ban offline players"
    default: op
  adminprotect.tempban.use.protected:
    description: "Access to temporary ban players with protection"
    default: op
  adminprotect.kick.protect:
    description: "Protection from /kick"
    default: op
  adminprotect.kick.use:
    description: "Access to use /kick"
    default: op
  adminprotect.kick.use.protected:
    description: "Access to kick players with protection"
    default: op
  adminprotect.unban.use:
    description: "Access to use /unban"
    default: op
  adminprotect.unbanip.use:
    description: "Access to use /unbanip"
    default: op
  adminprotect.banip.protect:
    description: "Protection from IP ban (if player online)"
    default: op
  adminprotect.banip.use:
    description: "Access to use /tempbanip"
    default: op
  adminprotect.banip.use.offline:
    description: "Access to ban offline players"
    default: op
  adminprotect.banip.use.protected:
    description: "Access to ban players with protection"
    default: op
  adminprotect.banip.use.permanent:
    description: "Access to use /banip for permanently ban IP"
    default: op